### ISSUE TITLE
MatlabBridge is not built for latest nightly and stable on Windows

### ISSUE THREAD

**Issue by lassoan** [PerkLab/SlicerMatlabBridge#5]
MatlabBridge is not built for latest nightly and stable on Windows maybe because of test errors in an extension that it depends on (SlicerOpenIGTLink).

http://slicer.cdash.org/viewTest.php?onlyfailed&buildid=1456789

**Comment by lassoan** [comment]
@Sunderlandkyl could you please fix or disable the failing tests in SlicerOpenIGTLink on Windows to check if indeed they prevent building of MatlabBridge.

**Comment by Sunderlandkyl** [comment]
Sure thing!

**Comment by Sunderlandkyl** [comment]
SlicerOpenIGTLink tests in nightly are now passing on Windows.
http://slicer.cdash.org/buildSummary.php?buildid=1457131

 Stable tests should be passing tomorrow.

MatlabBridge is now building properly on nightly:
http://slicer.cdash.org/buildSummary.php?buildid=1457153

**Comment by lassoan** [comment]
Thanks a lot @Sunderlandkyl!
